### ISSUE TITLE
Modal dialog opens behind the extension panel

### ISSUE THREAD

**Issue by WinkyW** [Adobe-CEP/CEP-Resources#93] opened 2016-12-07 16:59 UTC
Hi,

I have two Panel HTML extensions and one ModalDialog HTML extension. The Panel1 has a button that opens ModalDialog window using requestOpenExtension() function. I have issue that the ModalDialog is opened behind a Panel extension and the close (x) button is not visible, so I cannot close the ModalDialog. Because the application is in Modal status, I cannot move or close the Panel. Workaround I have to move the ModalDialog until the close (x) button is visible. But if the size of the Panel is very large and the ModalDialog is completely behind the Panel, it is not possible to drag and move the ModalDialog. Cannot close and read the content of the ModalDialog.

Any idea how this happened? Or any solutions?

PS 2015.5 and Windows 7

![photoshop2015_5_modaldialog](https://cloud.githubusercontent.com/assets/21666802/20977014/91123718-bca4-11e6-924f-1cd88a200e84.png)

![photoshop_details](https://cloud.githubusercontent.com/assets/21666802/20977019/95031b6c-bca4-11e6-8971-3d12e9202afd.png)

**Comment by akibnavidkhan** [comment] 2016-12-09 09:26
Hi WinkyW,

Can you please share the extension for debugging?

Thanks,
Akib

**Comment by akibnavidkhan** [comment] 2016-12-09 18:07
Hi WinkyW,

Thanks for sharing sample extension. I was unable to reproduce the issue in PS 2017 with Windows 10 and
PS 2015.5 with windows 7. Can you please give steps for reproducing issue?

**Comment by WinkyW** [comment] 2016-12-14 14:42
Hello Akib,

I added a video, so you could see what happened. This issue doesn't always occur, but when it occurs. It seems the issue is for all modal dialogs until I reset the Photoshop.

[PS_video.zip](https://github.com/Adobe-CEP/CEP-Resources/files/652006/PS_video.zip)

Hope you can reproduce it.
Thanks

**Comment by stompychump** [comment] 2016-12-26 01:31
I've struggled with this exact issue, which is intermittent but frequent. It only occurs in CC 2015+ in Windows 7 (and possibly 8), and only if the panel is free-floating. (In other words: it was not present in CC 2014, is fixed in Windows 10, does not occur in macOS, and does not occur in docked panels.)

If you examine the panel window stacking using any desktop window spy application (like WinExplorer <http://nirsoft.net/utils/winexp.html>), you can see that the panel is not relinquishing its Topmost status when another window is opened. This appears to be a bug in Photoshop's interaction with Windows 7's desktop window system.

The only solution I found for my projects was to write a small Win32 executable that fixed the panel window stacking state, and then to call that executable (using cep.process) from any controls in the panel that launch a window or dialog. Not elegant, but it mostly works.

**Comment by WinkyW** [comment] 2016-12-30 11:28
Hi stompychump,

Thank you for the explanation. I will try your workaround, do you have any sample code for me to try your solution?

Thanks

**Comment by stompychump** [comment] 2017-01-03 01:30
Sorry for the delay.

In general, the Win32 executable uses EnumWindows() to loop through all visible desktop windows looking for any with the class name "OWL.Dock" (a Photoshop free-floating HTML panel) or "OWL.FrameDrawer" (a panel opened from an icon). If any are found it uses SetWindowPos() and HWND_NOTOPMOST to re-set the stacking order. The executable could be written in any language that has Windows API libraries and can be compiled to a Win32 executable, but I used C:

`
function f() {

}
`

**Comment by stompychump** [comment] 2017-01-03 02:48
Sorry for the delay.

In general, the executable uses the Windows API  EnumWindows() function to loop through all visible desktop windows looking for any with the class name "OWL.Dock" (a Photoshop free-floating HTML panel) or "OWL.FrameDrawer" (a panel opened from an icon). If any are found it uses SetWindowPos() and HWND_NOTOPMOST to fix the stacking order. The executable could be written in any language that has WinAPI libraries and can be compiled to a Windows executable, but I used C:

```
#include <windows.h>

BOOL CALLBACK FindPanelWindow(HWND, LPARAM);
BOOL IsPanelWindow(HWND);
void LowerWindowBehindTopmost(HWND);

/**
 * Entry point.
 *
 * @param hInstance      HINSTANCE application handle
 * @param hPrevInstance  HINSTANCE application handle for previous instance (always NULL)
 * @param lpCmdLine      LPSTR command line
 * @param nCmdShow       int window display state
 *
 * @return               int execution status
 */
int WINAPI WinMain(
   HINSTANCE hInstance,
   HINSTANCE hPrevInstance,
   LPSTR lpCmdLine,
   int nCmdShow
   ) {

   /* Enumerate desktop windows to find Photoshop panel windows */
   EnumWindows(FindPanelWindow, (LPARAM)NULL);

   return 0;
}

/**
 * Find and lower a Photoshop panel window.
 *
 * @param window  HWND window handle
 * @param param   LPARAM window data (unused)
 *
 * @return        BOOL enumeration status
 */
BOOL CALLBACK FindPanelWindow(HWND window, LPARAM param) {

   /* Skip if the window is hidden */
   if (!IsWindowVisible(window)) {
      return TRUE;
   }

   /* If the window is a floating Photoshop HTML panel window, lower it */
   if (IsPanelWindow(window)) {
      LowerWindowBehindTopmost(window);
   }

   return TRUE;
}

/**
 * Check if a desktop window is a Photoshop HTML panel window.
 *
 * @param window  HWND window handle
 *
 * @return        BOOL
 */
BOOL IsPanelWindow(HWND window) {

   /* Class names of a floating Photoshop HTML panel window */
   const char *PANEL_CLASS_FLOAT = "OWL.Dock";        /* Free-floating */
   const char *PANEL_CLASS_ICON  = "OWL.FrameDrawer"; /* Opened from icon */

   /* Get the class name of the window */
   char windowClass[MAX_PATH];
   GetClassName(window, windowClass, sizeof(windowClass));

   /* Check for a panel window */
   if (strcmp(windowClass, PANEL_CLASS_FLOAT) == 0) {
      return TRUE;
   }
   else if (strcmp(windowClass, PANEL_CLASS_ICON) == 0) {
      return TRUE;
   }
   else {
      return FALSE;
   }
}

/**
 * Lower a desktop window to place it behind all topmost windows.
 *
 * @param window  HWND window handle
 */
void LowerWindowBehindTopmost(HWND window) {
   SetWindowPos(
      window,
      HWND_NOTOPMOST,
      0,
      0,
      0,
      0,
      SWP_NOMOVE | SWP_NOSIZE
   );
}
```

Note that this code will apply the fix to all free-floating HTML panels currently open in Photoshop, because I did not find a way to narrow the search to a particular panel. However this should be harmless, because the executable is only run when called from the currently active panel, and therefore all other panels are already lower in the stacking order.

The executable can be called from the panel using cep.process, which is documented in the "CEPEngine_extensions.js" script (available in this repository) and in Adobe's "Using the Adobe Extension SDK" PDF for CC 2014. Here's my general function:

```
/**
 * Run an external executable, optionally waiting for the process to terminate.
 *
 * @param exePath  string absolute path to executable
 * @param exeArgs  untyped executable argument or array of arguments
 * @param waitFor  boolean flag to wait for process to terminate
 *
 * @return         object process result (containing PID and error number)
 *
 * @see            "CEPEngine_extensions.js"
 */
function runExecutable(exePath, exeArgs, waitFor) {

   // Concatenate the executable path and arguments (if any) into an array
   var processArgs = [exePath].concat(exeArgs || []);

   // Run the executable
   var cepProcess     = window.cep.process;
   var createdProcess = cepProcess.createProcess.apply(cepProcess, processArgs);
   var processPID     = createdProcess.data;
   var processError   = createdProcess.err;
   var waitedProcess  = null;

   // Optionally wait for the process to terminate (NOTE: Blocks JS execution)
   if (waitFor && Number.isInteger(processPID) && processError === 0) {
      waitedProcess = cepProcess.waitfor(processPID);
      processError  = waitedProcess.err;
   }

   // Return the process ID and the error result
   return {
      pid:   processPID,
      error: processError
   };
}
```

To run this executable the exeArgs argument would be null, and in your case the waitFor argument would probably be best to set to true:

`runExecutable('C:/path/to/executable.exe', null, true);`

Note that path separators in the exePath string should be either "\\\\" (two backslashes) or "/" (one forward slash). To get the absolute path you will need the CSInterface.getSystemPath(SystemPath.EXTENSION) method.

Also note that in CC 2014 the Number.isInteger() JavaScript method is not native, so a polyfill is needed.

**Comment by WinkyW** [comment] 2017-01-09 08:42
Thanks for the sample code and your explanation!

**Comment by KupinFB** [comment] 2017-07-18 08:00
Hi. I had a same issue. It can be because of using of standart HTML "title" atribute. If you have the "title" and if it was shown once, you will have alot of problems with Z-index of Panels and Modal Windows.
I use not standart "tooltip libs" to show titles.
I will be glad if it helps you!

**Closed** 2020-09-10 11:55 UTC
