### ISSUE TITLE
[CEP-2241] CEP10: OOPS! Render process terminated

### ISSUE THREAD

**Issue by alebianco-doxee** [Adobe-CEP/CEP-Resources#322] opened 2020-10-27 13:12 UTC
I've a decently complex extension built in React that works ok in Animate 2020.

While upgrading to support Animate 2021 I noticed the extension crashes and the panel content reloads while attempting a HTTP PUT request to upload a file.

From the remote debugger I can't get any info on the cause. I managed to get something from the application logs (attached) but I can't understand if there's anything I can do to prevent the problem.

Any guidance is appreciated

[CEPHtmlEngine10-FLPR-21.0.0-com.adobe.flash.ToastNew.log](https://github.com/Adobe-CEP/CEP-Resources/files/5445482/CEPHtmlEngine10-FLPR-21.0.0-com.adobe.flash.ToastNew.log)
[CEPHtmlEngine10-FLPR-21.0.0-com.doxee.pvideo.panel.debug.log](https://github.com/Adobe-CEP/CEP-Resources/files/5445483/CEPHtmlEngine10-FLPR-21.0.0-com.doxee.pvideo.panel.debug.log)

**Comment by sujaisivanandan** [comment] 2020-10-27 14:29
Hi @alebianco-doxee, is the extension available on exchange that we can try?

**Comment by alebianco** [comment] 2020-10-27 14:35
hi @sujaisivanandan, yes it is https://exchange.adobe.com/creativecloud.details.100707.doxee-pvideo-for-animate-cc.html

only the version compatible with animate 2020 for now. if you need a build for 2021 to test, I can ask about sharing it though private channels

**Comment by alebianco-doxee** [comment] 2020-10-27 15:23
This is from the same session as the other two logs
[CEP10-FLPR.log](https://github.com/Adobe-CEP/CEP-Resources/files/5446272/CEP10-FLPR.log)

(been mixing my accounts but yeah, still me :D )

**Comment by sujaisivanandan** [comment] 2020-11-05 09:45
@alebianco-doxee Are you seeing this on Win and Mac both or is it Win Only?

**Comment by alebianco-doxee** [comment] 2020-11-05 10:57
same behaviour confirmed on both

side note:
i'm about to work (probably starting tomorrow) on building a smaller extension to isolate the problem and try to find a workaround. if I have any success i'll send it your way to help reproduce the issue and fix the root cause

**Comment by sujaisivanandan** [comment] 2020-11-05 11:05
Thanks @alebianco-doxee, that will be super helpful.

**Comment by alebianco-doxee** [comment] 2020-11-09 12:39
Hi @sujaisivanandan 
I managed to isolate the issue and create a tiny example of how to replicate the problem

https://gist.github.com/alebianco-doxee/62da443dfe577f566897d0391f18f3f9

Sadly, I haven't found a workaround yet. If you reckon there's something I can do while waiting for the final fix, please let me know

**Comment by alebianco-doxee** [comment] 2020-11-10 09:23
@sujaisivanandan sorry for the spam :D

found a workaround, commented on the gist. it's related to how the Buffer is created from the file content. maybe it helps to narrow down the issue further.

**Comment by rushilmahajan-adobe** [comment] 2020-11-19 03:52
Here you are Creating a Node object ( Buffer here ) and then passing that to Blob - which is a Web Object - Blob expects different forms ArrayBuffer - ArrayBuffer, ArrayBufferView, Blob, USVString
It is better to convert the NodeJs object(Buffer) to a Web object(Unit8Array).

You can refer to [https://stackoverflow.com/questions/8609289/convert-a-binary-nodejs-buffer-to-javascript-arraybuffer](https://stackoverflow.com/questions/8609289/convert-a-binary-nodejs-buffer-to-javascript-arraybuffer) on the conversion of Node Buffer to JS ArrayBuffer- Unit8Array,

CEP-10 uses NodeJS-12.0.3, This issue seems to be introduced in NodeJS 12 and fixed in NodeJS 14 version. For a better understanding of this issue and other workarounds, you can follow the electron issue discussion [https://github.com/electron/electron/issues/20750](https://github.com/electron/electron/issues/20750)


Posted the working code snippet in gist [https://gist.github.com/alebianco-doxee/62da443dfe577f566897d0391f18f3f9](https://gist.github.com/alebianco-doxee/62da443dfe577f566897d0391f18f3f9)

**Comment by alebianco** [comment] 2020-11-19 07:56
awsome, thanks for the clear explanation
I didn't think about the two contexts working together but it makes perfect sense 👍

**Comment by alebianco-doxee** [comment] 2020-11-19 07:57
awsome, thanks for the clear explanation 
I didn't think about the two contexts working together but it makes perfect sense 👍

**Comment by chris-at-cimpress** [comment] 2020-12-30 12:34
Is there a way to better isolate the cause of the crash? Like others, all I'm seeing is `ERROR --OOPS! Render process terminated---` in the logs as my extension crashes repeatedly in a loop. There really isn't much information to work with here. It looks like the crash is happening within third party code in my case, so it's not so straightforward to just eyeball the code.

**Comment by alebianco-doxee** [comment] 2021-01-04 07:44
@chris-at-cimpress not that I know of
I looked at every log and the only way I found was to dissect the project (code AND configurations) to find the line of code responsible. It's a bit of a pain.

**Comment by sujaisivanandan** [comment] 2021-03-24 09:16
@alebianco-doxee can this thread be closed? Was this issue resolved based on the explanation from @rushilmahajan-adobe ?

**Comment by alebianco-doxee** [comment] 2021-03-24 09:26
yes @sujaisivanandan it was resolved for me after the explanation

as @chris-at-cimpress said it would be useful to have something clearer in the logs when something like this happens, but this is not directly related to the issue to this thread can be closed for me

**Comment by sujaisivanandan** [comment] 2021-03-24 09:32
@alebianco-doxee  Sure that makes sense. FYI- we are already working on CEP 11 where we would be updating CEF and Node to the latest version(as of February 2021). So you should not see this in the next version.

**Closed by sujaisivanandan** 2021-03-24 09:32 UTC
Labels: bug
