### ISSUE TITLE
Get document bleeding size problem

### ISSUE THREAD

**Issue by DS0818** [Adobe-CEP/CEP-Resources#380] opened 2021-07-09 11:32 UTC
I checked illustrator_ JavaScript_ Scripting_ Reference_ In 2017, only the document bleeding documentbleedoffsetrect can be set, but the bleeding size that has been set in the document cannot be obtained. Is it because the document is incomplete or this method is not provided? Now how can I get the bleeding size of the current document. thank you!

**Comment by ramaadobe** [comment] 2021-07-14 17:09
@DS0818 Illustrator team is able to reproduce this issue. It will help prioritize this issue if you could report this issue in https://illustrator.uservoice.com/forums/601447-illustrator-desktop-bugs
-Rama
Illustrator Team

**Comment by sujaisivanandan** [comment] 2021-07-19 09:43
closing this here, since this can be taken up in the Illustrator forum.

**Closed by sujaisivanandan** 2021-07-19 09:43 UTC
